name: Build Plugin - Production

on:
  release:
    types: [created]
    
jobs:
  build:
    name: Build from publish.hxml using LunaWizard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: lix-pm/setup-lix@1.0.0
        with:
          node-version: 12
      - run: lix download
      - run: npm ci
      - run: npm run build:publish
      - name: Archive production build
        uses: actions/upload-artifact@v2
        with:
          name: production
          path: dist
